### ISSUE TITLE
Objective Unclear 

### ISSUE THREAD

**Issue by hrittikhere** [NavpreetDevpuri/Mindshap#1]
Hey Navpreet, 
I wasn't unable to understand the final objective for the following project. Can you kindly include the readme with Objective and what type of contribution do you seek in the following cause?

**Comment by NavpreetDevpuri** [comment]
Thank you so much for opening this issue 😌
I am little confused about how should i explain my thoughts. I am working on it i will update readme as soon as possible or i figured out what and how i can explain those details efficiently.
